# This is a basic workflow to help you get started with Actions

name: Build and Deploy Modules

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build All Modules
        run: dotnet build BlazorModular.sln --configuration Release

      - name: Copy DLLs to BackendAPI/wwwroot/dynamic
        run: |
          mkdir -p BackendAPI/wwwroot/dynamic
          cp Modules/*/bin/Release/net8.0/*.dll BackendAPI/wwwroot/dynamic/

      - name: Deploy to Server (if needed)
        run: |
          echo "Deploying to server..."
          # Put here SCP, FTP or command of deploy
