# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Deploy Modules

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore BlazorModular/BlazorModular.sln
        

      - name: Build All Modules
        run: dotnet build BlazorModular/BlazorModular.sln --configuration Release

      - name: Find changed modules
        id: find_modules
        run: |
            CHANGED_MODULES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^Modules/' | cut -d '/' -f2 | sort -u)
            echo "Found modules: $CHANGED_MODULES"
            echo "modules=$CHANGED_MODULES" >> $GITHUB_ENV


      - name: Build changed modules
        run: |
            for module in ${{ env.modules }}; do
              echo "Building module: $module"
              dotnet build Modules/$module/*.csproj --configuration Release
            done
        if: env.modules != ''

      - name: Copy DLLs to BackendAPI/wwwroot/dynamic
        run: |
            mkdir -p BlazorModular/BackendAPI/wwwroot/dynamic
            for module in ${{ env.modules }}; do
             cp Modules/$module/bin/Release/net9.0/*.dll BlazorModular/BackendAPI/wwwroot/dynamic/
            done
            if: env.modules != ''

      - name: Deploy to Server (if needed)
        run: |
          echo "Deploying to server..."
          # Put here SCP, FTP or command of deploy
